import uuid
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, List, Optional

from app.models.enums import (
    CapacityType,
    EventCategory,
    EventRegistrationStatus,
    EventSlot,
    EventVisibility,
    MemberRegistrationMode,
    RegistrationAvailability,
    RegistrationMode,
)
from app.schemas.event import EventDetail, EventListItem
from app.schemas.registration import RegistrationOut

DEMO_EVENTS_DATA = [
    {
        "id": uuid.UUID("10000000-0000-0000-0000-000000000001"),
        "name": "Code Genesis 2026",
        "tagline": "Speed, Logic & Algorithmic Supremacy",
        "short_desc": "Intense individual competitive programming round spanning standard algorithms and tricky edge cases.",
        "long_desc": "Code Genesis is KRATOS' flagship solo competitive programming contest. Tackle algorithmic challenges ranging from dynamic programming and graphs to combinatorial math in a timed ICPC-style arena.",
        "category": EventCategory.TECHNICAL,
        "coordinator": "Aarav Sharma",
        "coord_contact": "+91 98765 43210",
        "fee": Decimal("150.00"),
        "venue": "Computer Center Lab 3",
        "capacity": 120,
        "whatsapp_group_available": True,
        "starts_at": datetime(2026, 10, 15, 9, 30, tzinfo=timezone.utc),
        "ends_at": datetime(2026, 10, 15, 12, 30, tzinfo=timezone.utc),
        "slot": EventSlot.MORNING,
        "visibility": EventVisibility.PUBLISHED,
        "registration_status": EventRegistrationStatus.OPEN,
        "registration_open": True,
        "registration_availability": RegistrationAvailability.OPEN,
        "spots_remaining": 78,
        "team_min_size": 1,
        "team_max_size": 1,
        "required_member_count": 1,
        "substitute_count": 0,
        "allow_individual": True,
        "registration_mode": RegistrationMode.INDIVIDUAL_ONLY,
        "capacity_type": CapacityType.PARTICIPANTS,
        "member_registration_mode": MemberRegistrationMode.SELF_ENTRY,
        "allow_team_invite_flow": False,
        "requires_qr_checkin": True,
        "custom_fields": {"preferred_language": "C++/Python/Java"},
    },
    {
        "id": uuid.UUID("10000000-0000-0000-0000-000000000002"),
        "name": "KRATOS Flagship Hackathon",
        "tagline": "24 Hours of Pure Innovation",
        "short_desc": "Build transformative AI, Web3, and Open Innovation solutions in an exhilarating 24-hour overnight sprint.",
        "long_desc": "Gather your team and build working software prototypes that solve real-world problems in HealthTech, FinTech, EdTech, and Sustainability. Mentors, high-speed Wi-Fi, midnight snacks, and exciting sponsor tracks await!",
        "category": EventCategory.TECHNICAL,
        "coordinator": "Sneha Patel",
        "coord_contact": "+91 98765 43211",
        "fee": Decimal("600.00"),
        "venue": "Main Innovation Hub & Seminar Hall",
        "capacity": 60,
        "whatsapp_group_available": True,
        "starts_at": datetime(2026, 10, 15, 14, 0, tzinfo=timezone.utc),
        "ends_at": datetime(2026, 10, 16, 14, 0, tzinfo=timezone.utc),
        "slot": EventSlot.FULL_DAY,
        "visibility": EventVisibility.PUBLISHED,
        "registration_status": EventRegistrationStatus.OPEN,
        "registration_open": True,
        "registration_availability": RegistrationAvailability.OPEN,
        "spots_remaining": 22,
        "team_min_size": 2,
        "team_max_size": 4,
        "required_member_count": 2,
        "substitute_count": 0,
        "allow_individual": False,
        "registration_mode": RegistrationMode.TEAM_ONLY,
        "capacity_type": CapacityType.TEAMS,
        "member_registration_mode": MemberRegistrationMode.SELF_ENTRY,
        "allow_team_invite_flow": True,
        "requires_qr_checkin": True,
        "custom_fields": {"github_repo": "GitHub Repository URL", "project_track": "AI / Web3 / Open"},
    },
    {
        "id": uuid.UUID("10000000-0000-0000-0000-000000000003"),
        "name": "RoboWars: Steel & Fury",
        "tagline": "Heavyweight Metal Carnage",
        "short_desc": "15kg & 30kg combat robots fight inside the bulletproof steel arena for ultimate destruction.",
        "long_desc": "Watch spinning blades, pneumatic flippers, and armored wedges tear through opponent bots in a live battle cage with flame hazards and pit falls. Full safety gear mandatory in the pits.",
        "category": EventCategory.TECHNICAL,
        "coordinator": "Vikram Sethi",
        "coord_contact": "+91 98765 43212",
        "fee": Decimal("1000.00"),
        "venue": "Outdoor Combat Arena",
        "capacity": 32,
        "whatsapp_group_available": True,
        "starts_at": datetime(2026, 10, 16, 11, 0, tzinfo=timezone.utc),
        "ends_at": datetime(2026, 10, 16, 17, 0, tzinfo=timezone.utc),
        "slot": EventSlot.AFTERNOON,
        "visibility": EventVisibility.PUBLISHED,
        "registration_status": EventRegistrationStatus.OPEN,
        "registration_open": True,
        "registration_availability": RegistrationAvailability.OPEN,
        "spots_remaining": 14,
        "team_min_size": 2,
        "team_max_size": 5,
        "required_member_count": 2,
        "substitute_count": 1,
        "allow_individual": False,
        "registration_mode": RegistrationMode.TEAM_ONLY,
        "capacity_type": CapacityType.TEAMS,
        "member_registration_mode": MemberRegistrationMode.SELF_ENTRY,
        "allow_team_invite_flow": True,
        "requires_qr_checkin": True,
        "custom_fields": {"robot_weight_class": "15kg / 30kg", "weapon_type": "Drum Spinner / Flipper / Wedge"},
    },
    {
        "id": uuid.UUID("10000000-0000-0000-0000-000000000004"),
        "name": "Valorant Championship",
        "tagline": "Clutch or Kick — Campus Showdown",
        "short_desc": "5v5 competitive tactical shooter tournament on LAN servers with live shoutcasting.",
        "long_desc": "Double elimination tournament played on pristine 240Hz esports setups. Standard tournament map pool, coin toss for vetoes, and live finals on the grand auditorium main screen.",
        "category": EventCategory.PLAYGROUND,
        "coordinator": "Rohan Mehra",
        "coord_contact": "+91 98765 43213",
        "fee": Decimal("500.00"),
        "venue": "Esports Arena (Audi 2)",
        "capacity": 32,
        "whatsapp_group_available": True,
        "starts_at": datetime(2026, 10, 15, 10, 0, tzinfo=timezone.utc),
        "ends_at": datetime(2026, 10, 16, 20, 0, tzinfo=timezone.utc),
        "slot": EventSlot.MULTI_DAY,
        "visibility": EventVisibility.PUBLISHED,
        "registration_status": EventRegistrationStatus.OPEN,
        "registration_open": True,
        "registration_availability": RegistrationAvailability.OPEN,
        "spots_remaining": 8,
        "team_min_size": 5,
        "team_max_size": 6,
        "required_member_count": 5,
        "substitute_count": 1,
        "allow_individual": False,
        "registration_mode": RegistrationMode.TEAM_ONLY,
        "capacity_type": CapacityType.TEAMS,
        "member_registration_mode": MemberRegistrationMode.SELF_ENTRY,
        "allow_team_invite_flow": True,
        "requires_qr_checkin": True,
        "custom_fields": {"riot_id": "Riot ID with Tag", "rank": "Current Competitive Rank"},
    },
    {
        "id": uuid.UUID("10000000-0000-0000-0000-000000000005"),
        "name": "Design Sprint: UI/UX Odyssey",
        "tagline": "Empathy to Wireframes in 6 Hours",
        "short_desc": "Fast-paced product design challenge solving accessibility and user delight.",
        "long_desc": "Teams receive real problem statements from industry sponsors at 9 AM. Conduct rapid research, formulate user journeys, design high-fidelity Figma components, and pitch live to judges.",
        "category": EventCategory.TECHNICAL,
        "coordinator": "Ananya Joshi",
        "coord_contact": "+91 98765 43214",
        "fee": Decimal("200.00"),
        "venue": "Design Studio 4",
        "capacity": 40,
        "whatsapp_group_available": True,
        "starts_at": datetime(2026, 10, 16, 9, 0, tzinfo=timezone.utc),
        "ends_at": datetime(2026, 10, 16, 15, 0, tzinfo=timezone.utc),
        "slot": EventSlot.MORNING,
        "visibility": EventVisibility.PUBLISHED,
        "registration_status": EventRegistrationStatus.OPEN,
        "registration_open": True,
        "registration_availability": RegistrationAvailability.OPEN,
        "spots_remaining": 19,
        "team_min_size": 1,
        "team_max_size": 2,
        "required_member_count": 1,
        "substitute_count": 0,
        "allow_individual": True,
        "registration_mode": RegistrationMode.TEAM_OR_INDIVIDUAL,
        "capacity_type": CapacityType.PARTICIPANTS,
        "member_registration_mode": MemberRegistrationMode.SELF_ENTRY,
        "allow_team_invite_flow": True,
        "requires_qr_checkin": True,
        "custom_fields": {"portfolio_link": "Figma / Behance / Dribbble Link"},
    },
    {
        "id": uuid.UUID("10000000-0000-0000-0000-000000000006"),
        "name": "CyberSiege: 12-Hour CTF",
        "tagline": "Pwn, Reverse, Exploit & Defend",
        "short_desc": "Jeopardy-style capture the flag covering binary exploitation, web security, cryptography, and forensics.",
        "long_desc": "Built for security enthusiasts and ethical hackers. Discover hidden flags, decrypt custom ciphers, bypass authentications, and capture reverse shells in a sandboxed CTF environment.",
        "category": EventCategory.TECHNICAL,
        "coordinator": "Karan Gupta",
        "coord_contact": "+91 98765 43215",
        "fee": Decimal("300.00"),
        "venue": "Computer Systems Lab 1",
        "capacity": 45,
        "whatsapp_group_available": True,
        "starts_at": datetime(2026, 10, 15, 18, 0, tzinfo=timezone.utc),
        "ends_at": datetime(2026, 10, 16, 6, 0, tzinfo=timezone.utc),
        "slot": EventSlot.FULL_DAY,
        "visibility": EventVisibility.PUBLISHED,
        "registration_status": EventRegistrationStatus.OPEN,
        "registration_open": True,
        "registration_availability": RegistrationAvailability.OPEN,
        "spots_remaining": 15,
        "team_min_size": 1,
        "team_max_size": 3,
        "required_member_count": 1,
        "substitute_count": 0,
        "allow_individual": True,
        "registration_mode": RegistrationMode.TEAM_OR_INDIVIDUAL,
        "capacity_type": CapacityType.TEAMS,
        "member_registration_mode": MemberRegistrationMode.SELF_ENTRY,
        "allow_team_invite_flow": True,
        "requires_qr_checkin": False,
        "custom_fields": {"ctf_handle": "Handle/Username"},
    },
    {
        "id": uuid.UUID("10000000-0000-0000-0000-000000000007"),
        "name": "Battle of the Bands",
        "tagline": "Amps on 11, Riffs Unleashed",
        "short_desc": "Live acoustic and electric rock/fusion competition under stadium spotlights.",
        "long_desc": "Bands battle on the grand open-air stage for cash prizes and recording studio sessions. Professional sound engineering, full drum kit, and backline amps provided.",
        "category": EventCategory.CULTURAL,
        "coordinator": "Maya Nair",
        "coord_contact": "+91 98765 43216",
        "fee": Decimal("800.00"),
        "venue": "Grand Open Air Amphitheatre",
        "capacity": 16,
        "whatsapp_group_available": True,
        "starts_at": datetime(2026, 10, 17, 18, 0, tzinfo=timezone.utc),
        "ends_at": datetime(2026, 10, 17, 22, 30, tzinfo=timezone.utc),
        "slot": EventSlot.EVENING,
        "visibility": EventVisibility.PUBLISHED,
        "registration_status": EventRegistrationStatus.OPEN,
        "registration_open": True,
        "registration_availability": RegistrationAvailability.OPEN,
        "spots_remaining": 6,
        "team_min_size": 3,
        "team_max_size": 8,
        "required_member_count": 3,
        "substitute_count": 1,
        "allow_individual": False,
        "registration_mode": RegistrationMode.TEAM_ONLY,
        "capacity_type": CapacityType.TEAMS,
        "member_registration_mode": MemberRegistrationMode.SELF_ENTRY,
        "allow_team_invite_flow": True,
        "requires_qr_checkin": True,
        "custom_fields": {"band_genre": "Rock / Metal / Fusion", "equipment_requirements": "Special needs"},
    },
    {
        "id": uuid.UUID("10000000-0000-0000-0000-000000000008"),
        "name": "Street Dance Face-Off",
        "tagline": "Rhythm, Attitude & Freestyle Power",
        "short_desc": "1v1 and Crew vs Crew street dance, popping, locking, and breaking battles.",
        "long_desc": "DJ on the decks dropping spontaneous beats. Dancers enter the center cypher with 60-second rounds, evaluated by celebrity judges on musicality, originality, and execution.",
        "category": EventCategory.CULTURAL,
        "coordinator": "Dev Kapoor",
        "coord_contact": "+91 98765 43217",
        "fee": Decimal("300.00"),
        "venue": "Central Student Activity Center",
        "capacity": 50,
        "whatsapp_group_available": True,
        "starts_at": datetime(2026, 10, 16, 16, 0, tzinfo=timezone.utc),
        "ends_at": datetime(2026, 10, 16, 20, 0, tzinfo=timezone.utc),
        "slot": EventSlot.EVENING,
        "visibility": EventVisibility.PUBLISHED,
        "registration_status": EventRegistrationStatus.OPEN,
        "registration_open": True,
        "registration_availability": RegistrationAvailability.OPEN,
        "spots_remaining": 27,
        "team_min_size": 1,
        "team_max_size": 6,
        "required_member_count": 1,
        "substitute_count": 0,
        "allow_individual": True,
        "registration_mode": RegistrationMode.TEAM_OR_INDIVIDUAL,
        "capacity_type": CapacityType.TEAMS,
        "member_registration_mode": MemberRegistrationMode.SELF_ENTRY,
        "allow_team_invite_flow": True,
        "requires_qr_checkin": True,
        "custom_fields": {"dance_style": "Breaking / Popping / Krump / All-Styles"},
    },
]


def get_sample_event_list() -> List[EventListItem]:
    return [EventListItem.model_validate(d) for d in DEMO_EVENTS_DATA]


def get_sample_event_detail(event_id: uuid.UUID) -> Optional[EventDetail]:
    for d in DEMO_EVENTS_DATA:
        if d["id"] == event_id:
            return EventDetail.model_validate(d)
    return None
