"""HTF error codes and exceptions."""
from app.core.errors import AppError

# Stable HTF Error Codes from §66
SUBMISSION_DEADLINE_PASSED = "HTF_SUBMISSION_DEADLINE_PASSED"
INVALID_FILE_TYPE = "HTF_INVALID_FILE_TYPE"
FILE_TOO_LARGE = "HTF_FILE_TOO_LARGE"
SUBMISSION_FAILED = "HTF_SUBMISSION_FAILED"
SUBMISSION_NOT_FOUND = "HTF_SUBMISSION_NOT_FOUND"
NOT_SHORTLISTED = "HTF_NOT_SHORTLISTED"
PAYMENT_NOT_ELIGIBLE = "HTF_PAYMENT_NOT_ELIGIBLE"
PAYMENT_ALREADY_COMPLETED = "HTF_PAYMENT_ALREADY_COMPLETED"
PAYMENT_DEADLINE_PASSED = "HTF_PAYMENT_DEADLINE_PASSED"
PAYMENT_NOT_FOUND = "HTF_PAYMENT_NOT_FOUND"
INVALID_FEE = "HTF_INVALID_FEE"
APPLICATION_NOT_FOUND = "HTF_APPLICATION_NOT_FOUND"
APPLICATION_NOT_EDITABLE = "HTF_APPLICATION_NOT_EDITABLE"
NOT_TEAM_LEADER = "HTF_NOT_TEAM_LEADER"
NOT_TEAM_MEMBER = "HTF_NOT_TEAM_MEMBER"
SCREENING_NOT_ALLOWED = "HTF_SCREENING_NOT_ALLOWED"
DECISION_LOCKED = "HTF_DECISION_LOCKED"

# Gateway / webhook codes. Values are un-prefixed for compatibility with
# existing clients and tests; do not rename without a coordinated change.
GATEWAY_ERROR = "GATEWAY_ERROR"
BAD_REQUEST = "BAD_REQUEST"
FORBIDDEN = "FORBIDDEN"
PAYMENT_GATEWAY_NOT_CONFIGURED = "PAYMENT_GATEWAY_NOT_CONFIGURED"
WEBHOOK_SECRET_NOT_CONFIGURED = "WEBHOOK_SECRET_NOT_CONFIGURED"
MISSING_SIGNATURE = "MISSING_SIGNATURE"
INVALID_SIGNATURE = "INVALID_SIGNATURE"
INVALID_PAYMENT_SIGNATURE = "INVALID_PAYMENT_SIGNATURE"
INVALID_JSON = "INVALID_JSON"
AMOUNT_MISMATCH = "AMOUNT_MISMATCH"


def htf_error(code: str, message: str, status_code: int = 400) -> AppError:
    return AppError(code=code, message=message, status_code=status_code)
