"""
HTF 2026 – Team & Pass API endpoints (Member 2).

All routes are prefixed with /api/v1/htf.

Routes
------
POST   /htf/events/{event_id}/teams                 Create an HTF team
POST   /htf/teams/{team_id}/invitations             Generate invite link
GET    /htf/team-invitations/{invite_code}          Public invite preview
POST   /htf/team-invitations/{invite_code}/join     Join via invite
POST   /htf/teams/{team_id}/members/{member_id}/leave   Leave (roster-lock aware)
POST   /htf/teams/{team_id}/members/{member_id}/remove  Remove (roster-lock aware)

GET    /htf/events/{event_id}/problem-statements    List PS options
POST   /htf/teams/{team_id}/problem-statement       Leader selects PS

GET    /htf/teams/me/readiness                      Team readiness check
GET    /htf/pass                                    Participant digital pass
"""

import uuid

from fastapi import APIRouter, Depends, Query, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import get_current_profile
from app.db.session import get_db
from app.models.profile import Profile
from app.schemas.htf_team import (
    HTFPassOut,
    HTFProblemStatementOut,
    HTFSelectPSRequest,
    HTFTeamReadinessOut,
)
from app.schemas.team import (
    InvitationOut,
    InvitationPublicOut,
    JoinTeamResponse,
    TeamCreateRequest,
    TeamDetailOut,
    TeamMemberOut,
)
from app.services import htf_team_service, team_service

router = APIRouter(prefix="/htf", tags=["HTF 2026"])


# ── Team CRUD ─────────────────────────────────────────────────────────────────

@router.post(
    "/events/{event_id}/teams",
    response_model=TeamDetailOut,
    status_code=status.HTTP_201_CREATED,
    summary="Create an HTF team",
    description=(
        "Creates a new team for the HTF event. The creator becomes the **Leader** "
        "and their TeamMember status is immediately set to ACTIVE (no upfront payment "
        "required). An HTFTeamMeta row is also created with application_status=DRAFT. "
        "The caller must not already be in another active HTF team for this event."
    ),
)
async def create_htf_team(
    event_id: uuid.UUID,
    payload: TeamCreateRequest,
    db: AsyncSession = Depends(get_db),
    profile: Profile = Depends(get_current_profile),
):
    return await htf_team_service.create_htf_team(
        db, event_id=event_id, profile=profile, name=payload.name
    )


# ── Invite flow ───────────────────────────────────────────────────────────────

@router.post(
    "/teams/{team_id}/invitations",
    response_model=InvitationOut,
    summary="Generate an HTF team invite link",
    description=(
        "Generates (or returns the existing active) invite code for the team. "
        "Only the team leader can call this. The invite link should be shared as "
        "`https://htf.kratoseec.com/join/{code}`."
    ),
)
async def create_htf_invitation(
    team_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    profile: Profile = Depends(get_current_profile),
):
    # Reuse generic invite creation — roster-lock check is not needed here
    # (invites are generated by the leader; joining is where the lock matters)
    return await team_service.create_invitation(db, team_id=team_id, profile=profile)


@router.get(
    "/team-invitations/{invite_code}",
    response_model=InvitationPublicOut,
    summary="Preview HTF team invitation (public)",
    description=(
        "Returns team name, leader name, and slot availability for the given "
        "invite code. **No authentication required** — used to show the join "
        "preview page before the user logs in."
    ),
)
async def get_htf_invitation(
    invite_code: str,
    db: AsyncSession = Depends(get_db),
):
    return await team_service.get_invitation_public(db, invite_code=invite_code)


@router.post(
    "/team-invitations/{invite_code}/join",
    response_model=JoinTeamResponse,
    summary="Join an HTF team via invite link",
    description=(
        "Authenticated participant joins the team identified by `invite_code`. "
        "HTF-specific guards applied:\n"
        "- Roster is locked after application submission.\n"
        "- One active HTF team per participant (across the event).\n"
        "- Team capacity enforced under a `FOR UPDATE` row lock to prevent races."
    ),
)
async def join_htf_team(
    invite_code: str,
    db: AsyncSession = Depends(get_db),
    profile: Profile = Depends(get_current_profile),
):
    # We need the event_id. Resolve it from the invite code first.
    from sqlalchemy import select
    from app.models.team import Team, TeamInvitation

    inv_result = await db.execute(
        select(TeamInvitation).where(TeamInvitation.code == invite_code)
    )
    inv = inv_result.scalar_one_or_none()
    if not inv:
        from app.core.errors import AppError, HTF_INVITE_INVALID
        raise AppError(HTF_INVITE_INVALID, "Invalid invite code", status_code=404)

    team_result = await db.execute(select(Team).where(Team.id == inv.team_id))
    team = team_result.scalar_one_or_none()
    if not team:
        from app.core.errors import AppError, HTF_INVITE_INVALID
        raise AppError(HTF_INVITE_INVALID, "Team not found", status_code=404)

    return await htf_team_service.join_htf_team_via_invite(
        db,
        invite_code=invite_code,
        profile=profile,
        event_id=team.event_id,
    )


# ── Roster management (HTF-locked wrappers) ───────────────────────────────────

@router.post(
    "/teams/{team_id}/members/{member_id}/leave",
    response_model=TeamMemberOut,
    summary="Leave HTF team",
    description=(
        "Participant voluntarily leaves the team. "
        "**Blocked** once the application has been submitted (roster_locked=True)."
    ),
)
async def leave_htf_team(
    team_id: uuid.UUID,
    member_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    profile: Profile = Depends(get_current_profile),
):
    return await htf_team_service.leave_htf_team(
        db, team_id=team_id, member_id=member_id, profile=profile
    )


@router.post(
    "/teams/{team_id}/members/{member_id}/remove",
    response_model=TeamMemberOut,
    summary="Remove a member from HTF team",
    description=(
        "Team leader removes a member. "
        "**Blocked** once the application has been submitted (roster_locked=True)."
    ),
)
async def remove_htf_member(
    team_id: uuid.UUID,
    member_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    profile: Profile = Depends(get_current_profile),
):
    return await htf_team_service.remove_htf_member(
        db, team_id=team_id, member_id=member_id, profile=profile
    )


# ── Problem Statement ─────────────────────────────────────────────────────────

@router.get(
    "/events/{event_id}/problem-statements",
    response_model=list[HTFProblemStatementOut],
    summary="List available Problem Statements",
    description=(
        "Returns all active Problem Statements for the HTF event. "
        "Includes the number of teams that have claimed each PS "
        "and whether it requires a unique claim."
    ),
)
async def list_problem_statements(
    event_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    profile: Profile = Depends(get_current_profile),
):
    return await htf_team_service.list_problem_statements(db, event_id)


@router.post(
    "/teams/{team_id}/problem-statement",
    response_model=HTFTeamReadinessOut,
    summary="Select / change Problem Statement",
    description=(
        "Team leader picks (or changes) the Problem Statement. "
        "Only allowed while `application_status == DRAFT`. "
        "If the PS has `unique_claim=True`, the claim is first-come-first-served "
        "(backed by a `FOR UPDATE` row lock)."
    ),
)
async def select_problem_statement(
    team_id: uuid.UUID,
    payload: HTFSelectPSRequest,
    db: AsyncSession = Depends(get_db),
    profile: Profile = Depends(get_current_profile),
):
    return await htf_team_service.select_problem_statement(
        db, team_id=team_id, ps_id=payload.ps_id, profile=profile
    )


# ── Readiness & Pass ──────────────────────────────────────────────────────────

@router.get(
    "/teams/me/readiness",
    response_model=HTFTeamReadinessOut,
    summary="Team readiness report",
    description=(
        "Returns a full readiness report for the calling participant's team. "
        "The `is_ready` flag tells Member 1's dashboard whether to unlock "
        "the application submission button. The `blockers` list gives human-readable "
        "reasons if not ready."
    ),
)
async def get_team_readiness(
    event_id: uuid.UUID = Query(..., description="HTF Event ID"),
    db: AsyncSession = Depends(get_db),
    profile: Profile = Depends(get_current_profile),
):
    return await htf_team_service.get_team_readiness(
        db, profile=profile, event_id=event_id
    )


@router.get(
    "/pass",
    response_model=HTFPassOut,
    summary="Get participant digital pass",
    description=(
        "Returns the participant's digital entry pass for the HTF event. "
        "The `my_qr_token` field contains the unique QR token for venue check-in. "
        "Pass is ACTIVE only when `application_status == CONFIRMED` "
        "(i.e., payment has been received). "
        "The endpoint always returns data even if the pass is NOT_AVAILABLE — "
        "so the frontend can show 'payment pending' or 'shortlisted' context."
    ),
)
async def get_htf_pass(
    event_id: uuid.UUID = Query(..., description="HTF Event ID"),
    db: AsyncSession = Depends(get_db),
    profile: Profile = Depends(get_current_profile),
):
    return await htf_team_service.get_htf_pass(db, profile=profile, event_id=event_id)
