"""HTF Application and Dashboard specific error codes."""

HTF_APPLICATION_NOT_FOUND = "HTF_APPLICATION_NOT_FOUND"
HTF_APPLICATION_ALREADY_EXISTS = "HTF_APPLICATION_ALREADY_EXISTS"
HTF_APPLICATION_NOT_EDITABLE = "HTF_APPLICATION_NOT_EDITABLE"
HTF_TEAM_INCOMPLETE = "HTF_TEAM_INCOMPLETE"
HTF_APPLICATION_DEADLINE_PASSED = "HTF_APPLICATION_DEADLINE_PASSED"
HTF_APPLICATION_NOT_OPEN = "HTF_APPLICATION_NOT_OPEN"
HTF_NOT_A_TEAM_MEMBER = "HTF_NOT_A_TEAM_MEMBER"
